#!/bin/bash
# post conversion git tag & branch renaming
# Empty after renames
git branch -D releases
# Branch isn't informative
git branch -D irker-test-branch
# Rename stable tags
for tag in $(git tag -l | grep '^[0-9]\.[0,2,4,6,8]'); do
   git tag -f "stable/$tag" $tag
   git tag -d $tag
done

# Likewise unstable

for tag in $(git tag -l | grep '^[0-9]\.[1,3,5,7,9]'); do
   git tag -f "unstable/$tag" $tag
   git tag -d $tag
done

# Same for stable branches
for branch in $(git branch  | grep ' [0-9]\.[0,2,4,6,8]'); do
   git branch -M  $branch "stable/$branch"
done

for branch in $(git branch  | grep ' [0-9]\.[1,3,5,7,9]'); do
   git branch -M  $branch "unstable/$branch"
done

# Cleanup emptycommit and tipdelete tags

for tag in $(git tag -l | grep '^empty'); do
   git tag -d $tag
done

for tag in $(git tag -l | grep '^tipdelete'); do
   git tag -d $tag
done
